---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by oufy.
--- DateTime: 07/10/2020 00:35
---
trigger.action.setUserFlag("SSB",100)

humanUnits = {
    --Felix-1
    "unit|2|28|1001|F-14B| Pilot #1",
    "unit|2|28|1001|F-14B| Pilot #2",
    --Felix-2
    "unit|2|9|25|F-14B| Pilot #1",
    --Super
    "unit|2|6|25|F-16C_50| Pilot #1",
    "unit|2|6|25|F-16C_50| Pilot #2",
    "unit|2|6|25|F-16C_50| Pilot #3",
    --Frelon
    "unit|2|7|25|FA-18C_hornet| Pilot #1",
    --Hawg
    "unit|2|12|31|A-10C| Pilot #1",
    "unit|2|12|31|A-10C| Pilot #2",
    --Alouette
    "unit|2|14|31|Ka-50| Pilot #1",
    "unit|2|14|31|Ka-50| Pilot #2",
}

function getClientFromUnitName (_unitName)
    return CLIENT:FindByName(_unitName)
end

arrClients={}
for _unitIndex,_unitName in pairs(humanUnits) do
    arrClients._unitName = getClientFromUnitName(_unitName)
    arrClients._unitName:HandleEvent( EVENTS.Crash )
    function arrClients._unitName:OnEventCrash( EventData )
        self:E( "Crash de "..EventData.IniUnitName.." Le Flag ssb_"..EventData.IniUnitName.." va être fixé à 100" )
        trigger.action.setUserFlag("ssb_"..EventData.IniUnitName,100)
    end
    arrClients._unitName:HandleEvent( EVENTS.Ejection )
    function arrClients._unitName:OnEventEjection( EventData )
        self:E( "Ejection de "..EventData.IniUnitName.." Le Flag ssb_"..EventData.IniUnitName.." va être fixé à 100" )
        trigger.action.setUserFlag("ssb_"..EventData.IniUnitName,100)
    end
    --arrClients._unitName:HandleEvent( EVENTS.Dead )
    --function arrClients._unitName:OnEventDead(EventData)
    --    self:E( "Mort de "..EventData.IniUnitName.." Le Flag ssb_"..EventData.IniUnitName.." va être fixé à 100" )
    --    trigger.action.setUserFlag("ssb_"..EventData.IniUnitName,100)
    --end
end