---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by oufy.
--- DateTime: 27/10/2020 11:31
---

trigger.action.setUserFlag("SSB",100)

humanUnits = {
    --Felix-1
    "Felix-1-1",
    "Felix-1-2",
    --Super
    "Super-1-1",
    "Super-1-2",
    --Hyper
    "Hyper-1-1",
    "Hyper-1-2",
    --Frelon
    "Frelon-1-1",
    "Frelon-1-2",
    "Frelon-1-3",
    "Frelon-1-4",
    "Frelon-2-1",
    "Frelon-2-2",
    --Hawg
    "Hawg-1-1",
    "Hawg-1-2",
}

function getClientFromUnitName (_unitName)
    return CLIENT:FindByName(_unitName)
end

arrClients={}
for _unitIndex,_unitName in pairs(humanUnits) do
    arrClients._unitName = getClientFromUnitName(_unitName)
    arrClients._unitName:HandleEvent( EVENTS.Crash )
    function arrClients._unitName:OnEventCrash( EventData )
        self:E( "Crash de "..EventData.IniUnitName.." Le Flag ssb_"..EventData.IniUnitName.." va être fixé à 100" )
        trigger.action.setUserFlag("ssb_"..EventData.IniUnitName,100)
    end
    arrClients._unitName:HandleEvent( EVENTS.Ejection )
    function arrClients._unitName:OnEventEjection( EventData )
        self:E( "Ejection de "..EventData.IniUnitName.." Le Flag ssb_"..EventData.IniUnitName.." va être fixé à 100" )
        trigger.action.setUserFlag("ssb_"..EventData.IniUnitName,100)
    end
    --arrClients._unitName:HandleEvent( EVENTS.Dead )
    --function arrClients._unitName:OnEventDead(EventData)
    --    self:E( "Mort de "..EventData.IniUnitName.." Le Flag ssb_"..EventData.IniUnitName.." va être fixé à 100" )
    --    trigger.action.setUserFlag("ssb_"..EventData.IniUnitName,100)
    --end
end