groupBombe1 = GROUP:FindByName( "bombes-1" )
groupBombe1:Destroy()
groupBombe2 = GROUP:FindByName( "bombes-2" )
groupBombe2:Destroy()
groupBombe3 = GROUP:FindByName( "bombes-3" )
groupBombe3:Destroy()
groupBombe4 = GROUP:FindByName( "bombes-4" )
groupBombe4:Destroy()