---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by oufy.
--- DateTime: 15/11/2020 10:49
---
--ENABLE WITH TRUE, DISABLE WITH FALSE ENEMY AND FRIENDLY SQUADRONS FROM THE LIST BELOW
-- Skill, possible values "Average", "Good", "High", "Excellent" or "Random", yes, with with quotes

--//--ENEMY --//
Enable_CAT_Squadron = false
CAT_SQDN_Skill = "Excellent"

Enable_BEAR_Squadron = false
BEAR_SQDN_Skill = "Excellent"

Enable_TIGER_Squadron = false
TIGER_SQDN_Skill = "Excellent"

Enable_BOMBER_Squadrons = false

--//--ALLY --//
Enable_FALCON_Squadron = false
FALCON_SQDN_Skill = "Excellent"

Enable_HAWK_Squadron = false
HAWK_SQDN_Skill = "Excellent"

Enable_EAGLE_Squadron = false
EAGLE_SQDN_Skill = "Excellent"

--DISABLE UNWANTED PLANE GROUPS WITH TWO DASHES -- FROM THE POOL LIST BELOW:

--Example: --"☢ MiG-31",

RedCapPlanesLIST = {
    "☢ MiG-31",
    "☢ MiG-29S",
    "☢ MiG-21Bis",
    "☢ Su-27",
    "☢ Su-33",
    "☢ MiG-19P",
    "☢ MiG-23MLD",
    "☢ MiG-25PD",
    "☢ Su-34",
    --"☢ F5E3",
    --"☢ F-15C",
    --"☢ F-18C",
    "☢ F-14B",
    "☢ JF-17",
    "☢ J-11",
    "☢ Mirage 2000"
}

RedBombPlanesLIST = {
    "☢ Tu-22M3",
    "☢ Tu-142",
    "☢ Su-34AS",
    "☢ Su-25TM",
    "☢ Su-17M4",
    "☢ Su-24M",
    "☢ MiG-27K",
    "☢ Tornado"
}

BlueCapPlanesLIST = {
    "☮ F18",
    "☮ M2000",
    "☮ F14",
    "☮ F15",
    "☮ F16"
}

--DEFINE THE MAX AMMOUNT OF ALIVE PLANES FOR EACH SIDE BELOW:

TotalAliveRedPlanes = 0
TotalAliveBluePlanes = 0


--DEFINE CAP INTERVALS BELOW (IN SECONDS)

Cap_interval_min = 300
Cap_interval_max = 900

Bomber_interval_min = 600
Bomber_interval_max = 900