---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by oufy.
--- DateTime: 15/11/2020 10:46
---

--SET TRUE OR FALSE HERE TO ENABLE OR DISABLE MISSION FEATURES
--------
enable_BAI_tasks = true
enable_BAI_HARD_tasks = true
enable_AntiShip_tasks = true
enable_SEAD_tasks = true

enable_Helo_tasking = true
Enable_JTAC_Smoke = true
--------
enable_MissileTrainer = false
enable_ExtraDamage = true
enable_RescueHelos = true

enable_AirTraffic = true
MAX_Air_Traffic_Planes = 7

enable_CTDL = true
--------
enable_CSAR = true
CSAR_Time_Min = 300
CSAR_Time_Max = 600
--------
enable_ZEUS = true