---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by oufy.
--- DateTime: 15/11/2020 10:48
---
--DISABLE UNWANTED SEAD GROUPS WITH TWO DASHES -- FROM THE POOL LIST BELOW:

--Example: --"s3_red",

SEAD_GROUPS = {
    "s3_red",
    "s2_red",
    "s6_red",
    "hawk_red",
    "buk_red",
    --"s11_red",
    --"s10_red"
}