---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by oufy.
--- DateTime: 15/11/2020 10:47
---
--SET NUMERICAL VALUES FOR EACH OPTION, ALTITUDE IN FT SPEED IN KTS

Tanker_BOOM_Altitude = 19000
Tanker_BOOM_Speed = 360

Tanker_BOOM_Altitude_Low = 14000
Tanker_BOOM_Speed_Slow = 250

Tanker_BASKET_Altitude = 28000
Tanker_BASKET_Speed = 360