---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by oufy.
--- DateTime: 15/11/2020 10:47
---
--SET NUMERICAL VALUES FOR EACH OPTION, ALTITUDE IN FT SPEED IN KTS

Tanker_BOOM_Altitude = 10000
Tanker_BOOM_Speed = 310

Tanker_BASKET_Altitude = 25000
Tanker_BASKET_Speed = 310