enableAirboss = true
enablePedro = true
enableViking = true
enableHawkeye = true

CVN_UNIT_NAME = 'CVW-7-1'
CVN_TACAN_CHANNEL = 71
CVN_TACAN_BAND = 'X'
CVN_BASE_FREQ = 127.5
CVN_AIRBOSS_MARSHALL_FREQ = 127.4
CVN_AIRBOSS_LSO_FREQ = 127.6
CVN_ICLS_CHANNEL = 11


LHA_UNIT_NAME = 'CVW-7-9'
LHA_TACAN_CHANNEL = 99
LHA_TACAN_BAND = 'X'
LHA_BASE_FREQ = 127.7


airboss_enable_markzones = false
airboss_enable_smokezones = false
airboss_enable_niceguy = false

VIKING_ALTITUDE = 8000
VIKING_SPEED = 270
VIKING_TACAN_CHANNEL = 50
VIKING_TACAN_MORSE = 'ARC'
VIKING_FREQ = 264.5
VIKING_RACETRACK_FRONT = 50
VIKING_RACETRACK_AFT = 5

HAWKEYE_ALTITUDE = 22000
HAWKEYE_SPEED = 200
HAWKEYE_TACAN_CHANNEL = 51
HAWKEYE_TACAN_MORSE = 'MAG'
HAWKEYE_FREQ = 265.8
HAWKEYE_RACETRACK_FRONT = 50
HAWKEYE_RACETRACK_AFT = 50