---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by oufy.
--- DateTime: 15/11/2020 10:47
---

TankerBoomConfig = {
    enable = true,
    tacan = {
        channel = 55,
        morse = 'TEX',
    },
    freq = 264,
    altitude = 19000,
    speed = 360,
}

TankerBoomSlowConfig = {
    enable = true,
    tacan = {
        channel = 56,
        morse = 'SHL',
    },
    freq = 264.25,
    altitude = 14000,
    speed = 250,
}

TankerBasketConfig = {
    enable = true,
    tacan = {
        channel = 57,
        morse = 'ARC',
    },
    freq = 264.5,
    altitude = 28000,
    speed = 400,
}

AwacsConfig = {
    enable = true,
    tacan = {
        channel = 60,
        morse = 'OVR',
    },
    freq = 261,
    altitude = 37000,
    speed = 400,
}
